services:
  - type: static
    name: casino-frontend
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /admin/**
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html